service: dynamodb-stream-example
frameworkVersion: '2'
useDotenv: true

plugins:
  - serverless-dotenv-plugin

custom:
  streamArn: ${env:STREAM_ARN}
  accountId: ${env:ACCOUNT_ID}

provider:
  name: aws
  #  stage: dev
  #  region: us-east-1
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  memorySize: 2048 # Overwrite the default memory size. Default is 1024
  timeout: 60 # The default is 6 seconds. Note: API Gateway current maximum is 30 seconds

  iam:
    role:
      statements:  # IAM role statements so that services can be accessed in the AWS account
        - Effect: Allow
          Action:
            - 'logs:*'
          Resource:
            - 'arn:aws:logs:*:*:*'
        - Effect: Allow
          Action: # Gives permission to DynamoDB tables in a specific region
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:BatchWriteItem
            - dynamodb:BatchGetItem
            - dynamodb:DescribeStream
            - dynamodb:GetRecords
            - dynamodb:GetShardIterator
            - dynamodb:ListShards
            - dynamodb:ListStreams
          Resource:
            - 'arn:aws:dynamodb:*:${self:custom.accountId}:table/*'
            - 'arn:aws:dynamodb:*:${self:custom.accountId}:table/*/index/*'

package:
  patterns:
    - '!test/**'

functions:
  hello:
    handler: src/index.handler
    events:
      - stream: ${self:custom.streamArn}
